[package]
name = "miniglide"
version = "0.1.0"
edition = "2024"

[dependencies]
mint = "0.5.9"
na = { package = "nalgebra", version = "0.33.2", default-features = false, features = ["std", "mint"] }

[dev-dependencies]
approx = "0.5"
